export const Screens = {
  MAIN: 'MAIN',
  HOME: 'HOME',
  QUESTIONDETAILS: 'QUESTIONDETAILS',
  SIGNIN: 'SIGNIN',
  SIGNUP: 'SIGNUP',
  LANGUAGUES: 'LANGUAGUES',
  PROFILE: 'PROFILE',
  BOOKMARKS: 'BOOKMARKS',
};
